# Gunakan base image Node.js Alpine (ringan)
FROM node:20-slim

# Buat direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependensi
RUN npm install

# Salin semua file project ke dalam container
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Jalankan aplikasi dalam mode development
CMD ["npm", "run", "dev"]
