ALTER TABLE `SiteSetting` ADD COLUMN `logoUrl` VARCHAR(191) NULL;

CREATE TABLE `HomeContent` (
    `id` INTEGER NOT NULL DEFAULT 1,
    `heroImageUrl` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
